# Generated by Django 4.1.1 on 2023-08-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisualData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_year', models.PositiveIntegerField()),
                ('intensity', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('insight', models.TextField()),
                ('url', models.URLField()),
                ('region', models.CharField(max_length=100)),
                ('start_year', models.PositiveIntegerField()),
                ('impact', models.CharField(max_length=100)),
                ('added', models.DateTimeField()),
                ('published', models.DateField()),
                ('country', models.CharField(max_length=100)),
                ('relevance', models.CharField(max_length=100)),
                ('pestle', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('likelihood', models.CharField(max_length=100)),
            ],
        ),
    ]
