# Generated by Django 4.1.1 on 2023-08-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_visualdata_added_alter_visualdata_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualdata',
            name='published',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
